### ISSUE TITLE
error: failed to get domain 'Home'

### ISSUE THREAD

**Issue by AndyZaa** [Staffwerke/vm-babysitter#1]
Hi, Thanks for this great utility. I'm running the latest Unraid release, v6.12.14. I only have one VM, Home Assistant, that I hope to back up. I have most settings set to default except for the backup folder (on my array) and the backup chains (2).

I'm getting an "error: failed to get domain 'Home'". Am I missing a setting? Should I be able to get to a WebUI - there's no link to a UI.

MAX_BACKUPS_PER_CHAIN set to: 30
LOCAL_BACKUP_PATH set to: /backups
LOCAL_BACKUP_CHAINS_TO_KEEP set to: 2
RSYNC_BACKUP_PATH is not set

Configuring logrotate...
Configuring scheduled tasks...
Starting Cron...
Babysitter mode started...

==================================================================================================================================
Changes detected at: 2024-12-09 20:27:17 (America/New_York)

----------------------------------------------------------------------------------------------------------------------------------
Checking fileystem permissions for virtual disks...

error: failed to get domain 'Home'
Home: Has no virtual disks that can be backed up

WARNING: Issues found with at least one disk image paths of VM(s): Home, and therefore will be ignored. To solve this, take in mind that:
 - vm-babysitter cannot work with domains without virtual disks (e.g. transient machines)
 - Paths including virtual disks must be mounted equally at both host and container (e.g. '/mnt/user/domains:/mnt/user/domains')
 - If additional disks are under different paths, these has to be mounted in similar way as the above example
 - All paths and virtual disks must have both read and write permissions

==================================================================================================================================
Changed Status Summary:

Submitted for checks:      Home Assistant
Autostarted / powercycled: None
Passed all the checks:     None
Required new backup chain: None
Awaiting for shut down:    None
Failed during a check:     Home

Global Status (after changes):

Total running into scheduled backups: None
Total failed during checks or backup:  Home

All changes ended to be processed at 2024-12-09 20:27:18 (America/New_York)

**Comment by adrianparilli** [comment]
Hi @AndyZaa, that error shouldn't happen in first instance. First time I see it!

Just to let you know, VM-Babysitter doesn't have a WebGUI (At least for now). It's purely managed via docker options and console.

Into the context of your issue, VM-Babysitter detects all VMs first and then, it queries for virtual disks for all of them.

- In your case, the 1st step is happening correctly: 'Home' Vm is being detected.
- But the 2nd step is failing as if no VM existed at all, which is a contradiction itself. This never happened before.

We use Babysitter on v.6.12.13 without problems (and it has been tested heavily on v7.0.0-beta2). We haven't tested v.6.12.14 yet, but reading this [Unraid changelog](https://unraid.net/blog/6-12-14?srsltid=AfmBOopdIznDNKymJC9oqPpVfP_X3I4UghrQzaX90RCf7ag-BLZx0L0I) I don't find changes on libvirt API (which was my first suspect.)

Are you following [this](https://www.home-assistant.io/installation/linux/) tutorial by any chance for Home Assistant VM on Unraid using the qcow2 image?

**Comment by AndyZaa** [comment]
Thank you, @adrianparilli ! I installed Home Assistant using the spaceinvaderone HomeAssistant_inabox [https://github.com/SpaceinvaderOne/Home_Assistant_inabox](url) on the Unraid app store. It was an easy process which installed the app and qcow2 VM, and just worked with no fuss. Please let me know if there is any logs or details I can provide to assist troubleshooting.

**Comment by adrianparilli** [comment]
Hey @AndyZaa, I need the following to get started:

- Output of 2 specific commands
- XML definitions of your VM
- Main vm-babysitter's log file

For commands, open a terminal from Unraid's top right icons, then write the following commands:

```
virsh list --all --persistent --name
virsh domblklist --details <vm-name>
```
Replacing `<vm-name>` with the actual, case sensitive name of your VM.

If the second command **does not** return the same error you reported, I'm going to ask you to repeat commands 1 & 2, but inside the container. You can do this by opening container's console doing left click on vm-babysitter's icon (at Dashboard or Docker tabs).

vm-babysitter.log should be located at `/mnt/user/appdata/vm-babysitter/logs/` (assuming your environment is the default.)

To get VM definitions, you have 2 options:
- Either copy the file located at `/etc/libvirt/qemu/<vm-name>.xml` to a writable share
- Or run the following command from Unraid's console: `virsh dumpxml --inactive <vm-name> > /mnt/user/<some-path>/dump.xml`

Replacing `<vm-name>` just as before, and/or `<some-path>` with an actual path to any writable share to save `dump.xml` file.

Within your answer, please copy & paste the outputs of the `virsh` commands, and attach both .log and .xml files.

Regards,
Adrian.

**Comment by AndyZaa** [comment]
OK, Adrian ---
---------------------
from **both** Unraid terminal and vm-babysitter console

virsh list --all --persistent --name
returns
Home Assistant

virsh domblklist --details "Home Assistant"
returns
 Type   Device   Target   Source
 file   disk     hdc      /mnt/user/domains/Home Assistant/vdisk1.img
---------------------
I found the etc folder using Krusader but don't see a libvirt folder.

from Unraid terminal

virsh dumpxml --inactive "Home Assistant" > /mnt/user/data/downloads/dump.xml
returns
bash: /mnt/user/data/downloads/dump.xml: No such file or directory
---------------------

log is attached
[vm-babysitter.log](https://github.com/user-attachments/files/18086304/vm-babysitter.log)

Could the space in the VM name be a problem?

Thank you, 
Andy

**Comment by adrianparilli** [comment]
Definitively it's the space in VM name, @AndyZaa!

I'm able to reproduce the issue. It tries to search for a nonexistent VM called `Home` and fails.

In similar way, spaces in paths almost for sure will confuse the scripts, leading to unexpected errors (i.e: `/mnt/user/domains/Home Assistant/vdisk1.img`)

A quick solution for you would be to rename that VM to something like `Home-Assistant`, and ensure that path to disk image has no spaces (Unraid allows this transparently in most of cases). Thus, it will start running under scheduled backups.

But it's better to document yourself first about this change, since it might to cause HA container to complain. If this action is not contemplated, you might have to consider to start over, and choose a new VM name....

I'll look to solve this limitation in future versions. The only thing I can say now is, that's going to take some time...

Kind Regards,
Adrian.

**Comment by AndyZaa** [comment]
Yes, that worked!

Initial Backup Summary:
Successful backups: Home-Assistant
Failed backups:     None
Missing VMs:        None
Initial Backup ended at: 2024-12-10 21:31:26 (America/New_York)

I couldn't work out how to rename the VM and paths without creating new unique VMs so I just installed from scratch and restored a backup. I'll post on the spaceinvaderone HomeAssistant_inabox support forum so others can benefit.

Thank you, Adrian!
